### ISSUE TITLE
NOP

### ISSUE THREAD

**Issue by carlosmbpereira** [simprogrammingUaB/G1#2]
Teste

**Comment by masterdbpereira** [comment]
Como é que se apaga uma issue??

**Comment by masterdbpereira** [comment]
Como é que se apaga uma issue??

**Comment by machves** [comment]
boa pergunta;) Acho que podemos é fechar agora eliminar ;(

**Comment by carlosmbpereira** [comment]
Já deixei uma pergunta no Git da aplicação...vamos ver se o projecto ainda está vivo e se alguem responde.
Em ultimo caso, podemos sempre mudar-lhe o nome.

**Comment by machves** [comment]
Maravilha
Em 23/03/2016 21:07, "masterdbpereira" notifications@github.com escreveu:

**Comment by oafreitas74** [comment]
Vamos lá fazer o teste

**Comment by killercode** [comment]
As issues não se apagam por motivos de consistencia.... o que se pode fazer é fechar a issue

**Comment by carlosmbpereira** [comment]
@killercode, true! Abaixo a resposta da equipa de suporte do ZenHub
